name: Continuous Integration (CI)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan (Dry Run)
        run: terraform plan
