name: Deploy DB

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.6'  # ou a versão que você preferir

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'  # ou outra região

      - name: Terraform Plan
        run: terraform plan \
          -var="db_name=${{ secrets.RDS_DATABASE }}" \
          -var="db_username=${{ secrets.RDS_USERNAME }}" \
          -var="db_password=${{ secrets.RDS_PASSWORD }}"
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve \
          -var="db_name=${{ secrets.RDS_DATABASE }}" \
          -var="db_username=${{ secrets.RDS_USERNAME }}" \
          -var="db_password=${{ secrets.RDS_PASSWORD }}"
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'
