name: Deploy DB

on:
  workflow_dispatch: {}

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.6'

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="db_name=${{ secrets.RDS_DATABASE }}" \
            -var="db_username=${{ secrets.RDS_USERNAME }}" \
            -var="db_password=${{ secrets.RDS_PASSWORD }}"
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="db_name=${{ secrets.RDS_DATABASE }}" \
            -var="db_username=${{ secrets.RDS_USERNAME }}" \
            -var="db_password=${{ secrets.RDS_PASSWORD }}"
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    'us-east-1'

      - name: Retrieve DB endpoint
        id: get_endpoint
        run: |
          echo "DB_ENDPOINT=$(terraform output -raw db_endpoint)" >> $GITHUB_ENV

      - name: (Optional) Wait for RDS to be fully ready
        run: sleep 30

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Execute init.sql
        run: |
          # Se seu arquivo estiver em outro lugar, ajuste o caminho
          # Exemplo: scripts/init.sql ou migrations/init.sql
          psql "postgres://${{ secrets.RDS_USERNAME }}:${{ secrets.RDS_PASSWORD }}@${{ env.DB_ENDPOINT }}/${{ secrets.RDS_DATABASE }}" -f init.sql
